wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1670399425.757031
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 23
      4: 3.8.10
      5: 0.13.6
      8:
      - 5
